/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from '@aws-amplify/data-schema';
import { configure } from '@aws-amplify/data-schema/internals';
import { secret } from '@aws-amplify/backend';

export const schema = configure({
	database: {
		identifier: 'IDAGE1oSPNC5zUgGdMMbr7g',
		engine: 'mysql',
		connectionUri: secret('SQL_CONNECTION_STRING'),
		vpcConfig: {
			vpcId: 'vpc-dd670bb5',
			securityGroupIds: ['sg-026cafcc6dbf35151'],
			subnetAvailabilityZones: [
				{
					subnetId: 'subnet-df670bb7',
					availabilityZone: 'us-west-2b'
				},
				{
					subnetId: 'subnet-de670bb6',
					availabilityZone: 'us-west-2a'
				}
			]
		}
	}
}).schema({
	profiles: a
		.model({
			id: a.string().required(),
			user_id: a.string().required(),
			name: a.string().required(),
			email: a.string().required(),
			created_at: a.datetime(),
			updated_at: a.datetime()
		})
		.identifier(['id'])
		.authorization((allow) => [allow.authenticated(), allow.guest()]),
	puzzles: a
		.model({
			id: a.string().required(),
			puz_json: a.string().required(),
			puz_key: a.string(),
			title: a.string(),
			author: a.string(),
			created_at: a.datetime(),
			updated_at: a.datetime()
		})
		.identifier(['id'])
		.authorization((allow) => [allow.authenticated(), allow.guest()]),
	user_puzzles: a
		.model({
			id: a.string().required(),
			profile_id: a.string().required(),
			puzzle_id: a.string().required(),
			used_check: a.integer().required(),
			used_reveal: a.integer().required(),
			used_clear: a.integer().required(),
			time_in_seconds: a.integer().required(),
			created_at: a.datetime(),
			updated_at: a.datetime()
		})
		.identifier(['id'])
		.authorization((allow) => [allow.authenticated()])
});
