/// <reference lib="webworker" />

import { build, files } from '$service-worker';
import { shouldHandleFetch, deleteOldCaches, fetchAndCache } from './service-worker-helpers';

const timestamp = Date.now();
const worker = self as unknown as ServiceWorkerGlobalScope;
const FILES = `cache${timestamp}`;
const OFFLINE_CACHE = `offline${timestamp}`;

// `build` is an array of all the files generated by the bundler,
// `files` is an array of everything in the `static` directory
const to_cache = build.concat(files);
const staticAssets = new Set(to_cache);

worker.addEventListener('install', (event) => {
	event.waitUntil(
		caches
			.open(FILES)
			.then((cache) => cache.addAll(to_cache))
			.then(() => {
				worker.skipWaiting();
			})
	);
});

worker.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			await deleteOldCaches(keys, FILES);
			worker.clients.claim();
		})
	);
});

worker.addEventListener('fetch', (event) => {
	const { request } = event;
	const url = new URL(request.url);
	const isStaticAsset = url.host === self.location.host && staticAssets.has(url.pathname);

	const shouldHandle = shouldHandleFetch(
		request.method,
		request.headers.has('range'),
		url.protocol,
		url.hostname,
		url.port,
		self.location.hostname,
		self.location.port,
		request.cache,
		isStaticAsset
	);

	if (shouldHandle) {
		event.respondWith(
			(async () => {
				const cachedAsset = isStaticAsset && (await caches.match(request));
				return cachedAsset || fetchAndCache(request, OFFLINE_CACHE);
			})()
		);
	}
});
